TDD 적용과 코드 개선 2
xfrnk2/restaurant_simulation pull request #11
Opened 2020-11-01 15:01 UTC by xfrnk2

TDD 적용과 코드 개선 2

2020-11-04 08:00 UTC, zrma requested changes

2020-11-04 08:00 UTC, zrma commented on src/restaurant.py
> +    if not_taken_order:
early return 하면 어떨까요?

```python
if not not_taken_order:
    return 0

result = 0
while not_taken_order:
    ....

return result
```

2020-11-04 08:00 UTC, zrma commented on src/restaurant.py
> +def calc_remaining_time_part1(not_taken_order, taken_order):
이 함수는 뭘 하는 함수일까요?

2020-11-04 08:00 UTC, zrma commented on src/restaurant.py
> +        while not_taken_order:
여기 뭔가 최적화 할 여지가 보이네요.

2020-11-07 13:55 UTC, zrma requested changes

2020-11-07 13:55 UTC, zrma commented on src/restaurant.py
> +    tables = list(filter(lambda x: x <= waitable_time, tables))
이렇게 되면 쓸데 없이 임시 객체 list를 만들어서 그 length를 체크하니까

```python
for time in tables:
    if time > waitable_time:
        continue
    waitable_amount -= 1
    if waitable_amount < 0:
        return True
return False
```

내지는 

```python
for time in tables:
    if time <= waitable_time:
        waitable_amount -= 1
return waitable_amount < 0
```

이런 식이면 어떨까요?

2020-11-07 13:55 UTC, zrma commented on tests/restaurant_test.py
> +                     ),
각 테스트 케이스의 description이 들어가도 좋을 것 같군요.\
그리고 그 description을 아래의 `assert cond, msg` 구문의 msg 항목에 넣을 수 있을 것 같아요.

2020-11-13 02:31 UTC, zrma requested changes
지금 뭔가 충분히 복잡하니까 \
새로운 기능을 추가하면서 테스트 코드를 자꾸 늘리기보다는\
기존의 코드들의 테스트 커버리지를 늘려가면서\
오히려 기존의 코드량을 줄이는 식으로 작업하면 어떨까요?

2020-11-13 02:31 UTC, zrma commented on src/restaurant.py
> +            table_idx += idx
이러면 그냥 `return idx` 하고 아래에서는 return 0 하면 되는 거 아니에요?

2020-11-13 02:31 UTC, zrma commented on src/restaurant.py
> +    return f"{customer_num}번 손님이 {table_idx+1}번 테이블에 앉습니다.\n{customer_num}번 손님이 {num}번 요리({food_name[num]})를 주문합니다."
이건 지금은 아니고 나중에 리팩토링 할 때 신경 쓸 문제이긴 한데요\
텍스트 출력을 위임할 객체를 하나 설계하면 좋겠네요.

나머지 객체들은 각자 할 일을 하고, 중간 중간 어떤 결과물을 해당 객체의 대기 큐 같은데에 저장해두면\
해당 큐가 출력을 전담하는거죠.

그래서 restaurant나 customer, cook, table 등에는 출력 메세지 텍스트가 다 사라지면 좋겠군요.

2020-11-13 02:31 UTC, zrma commented on src/restaurant.py
> +    return {"is_eating": False, "eating_time": food_eating_time[num], "customer_num": customer_num}
이런 dict는 별로 좋진 않은 것 같아요.

2020-11-13 02:31 UTC, zrma commented on src/restaurant.py
> +    return [food_cooking_time[num], {"customer_num": customer_num, "num": num, "table_idx": table_idx}]
반환 타입이 어떤 의미인지 모르겠어요.

왜 list?

2020-11-13 02:31 UTC, zrma commented on src/restaurant.py
> +    if cooks:
early return.

2020-11-13 02:31 UTC, zrma commented on src/restaurant.py
> +                idx += 1
이게 대충

```python
finished_orders = _cooks[:cook[0]]
```
이걸 하고 싶어서 그런거죠?

그리고 위에서 `_cooks = cooks[:]` 이걸 한 이유는 아래에서 `cook[0] -= 1`을 하다보니 원본 데이터가 오염되니까\
그걸 방지하기 위해서 복사하려고 한거고요?

애초에 필요한 만큼 잘라서 반환하면 이렇게 할 필요가 없지 않을까요?

2020-11-13 02:31 UTC, zrma commented on src/restaurant.py
> +        idx += 1
```python
if not table["is_eating"]:
    idx += 1
    continue
if 0 < table["eating_time"]:
    table["eating_time"] -= 1
if table["eating_time"] <= 0:
    finished_tables.append(tables.pop(idx))
```

이러면 뭔가 한 depth 얕아질텐데...

2020-11-16 14:54 UTC, xfrnk2 commented on src/restaurant.py
> +    return [food_cooking_time[num], {"customer_num": customer_num, "num": num, "table_idx": table_idx}]
@zrma 경과시간만 수정할수 있는 형태로 하려다보니 그랬던 것 같아요.
혹시 좀 다른 이야기지만 한가지 궁금한 것 여쭤봐도 될까요?

immutable한 namedtuple이나 dataclass 객체의 원소를 메서드를 통해 1회 바꾼다고 가정했을때, 성능상 저하가 무시 못할 수준일까요? 어느정도인지 궁금해요.

2020-11-19 06:43 UTC, zrma approved these changes
이 PR은 이 정도로 정리하면 어떨까요?

다음 PR부터는 작업의 방향을 정해서 한 가지 일을 처리하는 식으로\
작업의 규모를 줄이는 것이 좋을 것 같아요.

2020-11-19 06:43 UTC, zrma commented on tests/restaurant_test.py
> +CustomerInitCase = namedtuple("CustomerInitCase", "customer_num food_num expected")
[namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple) 대신 [dataclass](https://docs.python.org/3/library/dataclasses.html)를 써 보면 어떨까요?

2020-11-23 02:43 UTC, xfrnk2 commented on tests/restaurant_test.py
> +CustomerInitCase = namedtuple("CustomerInitCase", "customer_num food_num expected")
@zrma 감사합니다 (_ _)

2020-11-23 02:43 UTC, merged