TDD 적용과 코드 개선 3
xfrnk2/restaurant_simulation pull request #12
Opened 2020-11-23 13:48 UTC by xfrnk2

TDD 적용과 코드 개선 3

2020-11-29 12:03 UTC, zrma requested changes
코드가 많이 복잡해보이네요.

기존의 코드를 지속적으로 간결하게 줄이는 데 집중해 보세요.

2020-11-29 12:03 UTC, zrma commented on src/restaurant.py
> +class CustomerInfo(NamedTuple):
[typing](https://docs.python.org/3/library/typing.html) 모듈은 타입힌트를 위한 용도지 이렇게 상속하는 용도는 아닌 것 같아요.

2020-11-29 12:03 UTC, zrma commented on src/restaurant.py
> +    result = []
```python
return [ k for k, v in tables.items() if not v ]
```

2020-11-29 12:03 UTC, zrma commented on src/restaurant.py
> +    return [0, food_eating_time[num], customer_num]
반환 값의 의미를 잘 모르겠어요.

0번 index의 값을 왜 False에서 0으로 수정하였나요?\
False의 의미도, 0의 의미도 모르겠어요.

2020-11-29 12:03 UTC, zrma commented on src/restaurant.py
> +    return [food_cooking_time[num], customer_num, num, table_idx]
반환 list의 각 인덱스의 의미를 모르겠어요.

2020-11-29 12:03 UTC, zrma commented on src/restaurant.py
> +    cooks = sorted(cooks, key=lambda x: x[0])
`x[0]`의 의미를 모르겠어요.\
그러니까 왜 이 값을 기준으로 정렬하는지도 모르겠어요.

이런 코드는 되게 안 좋은 코드인 것 같아요.\
이 함수만 보고 이 함수의 문맥이 이해가 안 가기 때문에 결국 caller를 살펴봐야 하죠.\
그러면 해당 caller에서도 이 `cooks`라는 list가 뭔지 이해가 안 가기 때문에\
이전에 호출한 함수(callee)를 열어봐야만 하죠.

이런 코드는 안 좋은 것 같습니다.

2020-11-29 12:03 UTC, zrma commented on src/restaurant.py
> +        cooks[i][0] -= 1
`cooks`의 의미를 모르겠으니까 `cooks[i][0] -= 1` 에서 왜 1씩 빼 주는 지 모르겠어요.

2020-11-29 12:03 UTC, zrma commented on src/restaurant.py
> +        if cook[0] < 1:
cook_finished 뭐 대충 이런 문맥의 boolean 일 것 같긴 한데\
이 조건식만 봐서는 무슨 의미인지 모르겠어요.

2020-11-29 12:03 UTC, zrma commented on src/restaurant.py
> +            tables[i][0] += 1
`for i, table in enumerate(tables):` 해당 구문에서 이미 table을 꺼냈는데\
여기서 다시 `tables[i][0]`을 쓸 필요 없지 않나요?

2020-11-29 12:03 UTC, zrma commented on src/restaurant.py
> +            tables[i][0] += 1
그리고 `table[0]`이 무슨 의미인지 모르겠어요.

2020-11-29 12:03 UTC, zrma commented on src/restaurant.py
> +    def add(sign: str, info: tuple):
info로 tuple을 써버리니까 결국 이 `PrintOut`이라는 클래스는 전반적으로 출력이 필요한 모든 곳에 강하게 결합되어 버려요.

결국 이 `add` 함수를 호출하는 모든 부분에서 아래의 함수 `printout`의 내부 로컬 자료구조의 키 값인\
`arrive, back, order_request, start, finish, leave` 같은 하드코딩 값들을 알아야만 하는거죠.

이런 코드 되게 나쁜 코드인 것 같아요.

2020-11-29 12:03 UTC, zrma commented on src/restaurant.py
> +        __class__.__queue = []
staticmethod인데 여기서 __class__ 에 접근하고 이런 것 안 좋아보여요.

classmethod를 쓰면 안 되는 걸까요?

그런데 애초에 singleton으로 객체를 만들면 안 되는 걸까요?

2020-11-29 12:03 UTC, zrma commented on tests/restaurant_test.py
> +from dataclasses import dataclass
뭔가 동어 반복적인 자료구조가 많아 보이네요.

아직 코드가 복잡해보여요.

2020-12-05 20:53 UTC, zrma commented on src/restaurant.py
> +        if table[0] <= waitable_time:
table[0]은 무엇?

2020-12-05 20:53 UTC, zrma commented on src/restaurant.py
> +class CustomerInfo(NamedTuple):
이건 아직도 이 상태네요.

2020-12-05 20:53 UTC, zrma commented on src/restaurant.py
> +    return f"{max(tables.values(), key=lambda x: x[0])[0]}분 이상"
코드가 점점 복잡해지는 것 같아요.

2020-12-05 20:53 UTC, zrma commented on src/restaurant.py
> +        if value == [0, 0, 0]:
value == [0, 0, 0] 는 무엇?

2020-12-06 11:09 UTC, xfrnk2 commented on src/restaurant.py
> +class CustomerInfo(NamedTuple):
@zrma 감사합니다. (_ _) 
기존 restaurant.py 외에 restaurant_1, restaurant_2로 파일을 생성해서 그동안 수정 작업을 해보고 있었는데 따로 빼서 참고 하면서 현재 진행중인 것을 restaurant.py파일에 넣을 걸 그랬어요.  전체적인 구조를 빠르게 바꿀 엄두가 안나서 그랬는데 이제 바꾸었어요.

2020-12-06 22:26 UTC, zrma approved these changes
코드가 꽤 정리 됐네요.

.exe 바이너리를 커밋했는데 삭제해주세요.

이 PR은 이 정도로 정리하고 다음엔 PrintOut를 정리해보죠.

2020-12-06 22:26 UTC, zrma commented on src/bill.py
> +        self.__time = 5
하드코딩 5는 의미 있는 상수 변수로 빼는 게 좋을 것 같아요.

2020-12-06 22:26 UTC, zrma commented on src/cook.py
> +    def waiting_time(self):
이런 함수는 로직이 복잡하니 코멘트를 적절히 작성하는게 어떨까요?

2020-12-07 13:38 UTC, merged