TDD 적용과 코드 개선 4 & PrintOut 정리
xfrnk2/restaurant_simulation pull request #13
Opened 2020-12-07 13:57 UTC by xfrnk2

TDD 적용과 코드 개선 4 & PrintOut 정리

2020-12-26 17:23 UTC, zrma approved these changes

2020-12-26 17:23 UTC, zrma commented on src/cook.py
> +        '''
함수의 설명 주석은 함수 선언 바로 아래 적어야 합니다.

`result = 0` 과 위치를 바꿔주세요.

2020-12-26 17:23 UTC, zrma commented on tests/table_test.py
> +class TableInstance:
class 이름이 `Instance` 인 건 조금 이상한 것 같아요.

t = tableInstance()

t는 테이블 인스턴스의 인스턴스 인가요?

2020-12-26 17:23 UTC, zrma commented on tests/table_test.py
> +class IsWaitableCase:
보통 Is~~~ 는 boolean [POD](https://en.wikipedia.org/wiki/Passive_data_structure)에 붙이는 이름 같아요.

2020-12-26 17:23 UTC, zrma commented on src/restaurant.py
> +            Printout.add(f'손님이 기다릴 수 없어 돌아갑니다. 현재대기시간 {self.__table.waitable_time}분 / 대기가능시간 {time}분')
이런 경우 전달하고자 하는 메세지에 해당하는 이벤트를 제한 된 타입으로 생성하고

PrintOut은 각 구성요소와 그 이벤트 메세지로 통신하는 것이 어떨까 합니다.

2020-12-27 07:56 UTC, zrma requested changes

2020-12-27 07:56 UTC, zrma commented on src/cook.py
> +                # 소요시킬 소요시간만큼 리스트 내 모든 원소의 값을 감소시켜 0을 만듭니다.
이런 식으로 주석을 line by line으로 작성하다보면 코드와 주석이 동어 반복하게 됩니다.\
이렇게 주석을 달아야만 코드가 이해된다면 뭔가 코드에 문제가 있는 거라 리팩토링이 필요해 보입니다.

2020-12-27 07:56 UTC, zrma commented on src/restaurant.py
>              if not self.time % period:
%([modulo](https://en.wikipedia.org/wiki/Modulo_operation))는 [산술연산](https://en.wikipedia.org/wiki/Arithmetic)이라서 [논리연산](https://en.wikipedia.org/wiki/Mathematical_logic)에 적합한 `not`은 직관적이지 않은 것 같스빈다.

수식을 그대로 사용하는 편이 더 좋을 것 같아요.
```python
if self.time % period == 0:

# 또는

is_remained = self.time % period
if not is_remained:
```

2020-12-27 07:56 UTC, zrma commented on src/restaurant.py
> +            Printout.out()
`PrintOut.printout`이나 `Printout.out`이나 둘 다 조금 이상해보여요.

2020-12-27 07:56 UTC, zrma commented on src/table.py
>  class Table:
`class Table` 의 `def update(self)` 함수에서

```python
for i in self.table.keys():
    if not isinstance(self.table[i], Customer):
        continue
```

이 부분(`isinstance`를 사용해야만 하는 구조가)이 조금 찜찜해요.

2020-12-27 07:56 UTC, zrma commented on tests/bill_test.py
> +        assert bill.waiting == case.expected
property로 외부에 노출 한 것도 아닌데 이렇게 접근해서 무언가를 하는게 조금 이상해 보여요.

중간에 코드를 보다보면 
`Restaurant`의 메소드에서 `self.__bill.waiting.extend(self.__table.update())` 이런 식으로 접근하던데\
이거 조금 이상한 구조인 것 같아요.

남의 주머니 안에 있는 지갑에 든 돈을 꺼내는 느낌이랄까요

2020-12-27 07:56 UTC, zrma commented on tests/table_test.py
> +            self.table.table[i] = Customer(CustomerInfo(i, i, 0), 0, time)
CustomerInfo의 `i, i, 0`이 뭘 의미하는지 모르겠어요.\
이런 경우는 [keyword arguments](https://www.w3schools.com/python/gloss_python_function_keyword_arguments.asp)가 코드 가독성을 올려줄 것 같아요.

2021-01-17 14:06 UTC, zrma requested changes

2021-01-17 14:06 UTC, zrma commented on tests/table_test.py
> +sys.path.append('C:/Users/rad87/Documents/programming/restaurant_simulation')
이런 user specific 한 정보는 빼는 것이 좋습니다.

2021-02-05 10:34 UTC, zrma approved these changes

2021-02-05 10:35 UTC, zrma commented
한 PR의 커밋 내용이 너무 길어졌군요.\
이건 이 정도로 정리하는게 어떨까요?

2021-02-05 14:04 UTC, xfrnk2 commented
@zrma 감사합니다!

2021-02-05 14:05 UTC, merged