#1~#2 README.md 수정, PEP8에 맞게 내용 수정
xfrnk2/restaurant_simulation pull request #6
Opened 2020-08-26 16:50 UTC by xfrnk2

#### Issue
> #1 README.md 보강하기
> #2 PEP위반 ; 문서의 개행 누락
  
#### Changes
+ README.md 파일 수정하였습니다.
+ flake8 모듈을 사용해서 전체 코드가 PEP8 기준에 알맞은 코드가 되도록 reformat 하였습니다.

2020-08-27 00:34 UTC, zrma requested changes
이 수정 내용에 대한 언급은 아니지만 
코드를 살펴보니 전체적으로 무언가 기교를 부리려고 한 듯한 느낌이 듭니다. #3 

https://rinae.dev/posts/the-faster-you-unlearn-oop-the-better-for-you-and-your-software-kr

이 글을 차근 차근 한 번 읽어보고 전체적으로 코드에서 불필요하거나 걷어낼 수 있는 부분은
많이 줄여서 코드를 간결하게 만들면 좋을 것 같습니다.

정말 필요한 역할만 수행하는 최소한의 코드만 있으면 좋을 것 같아요.

2020-08-27 00:34 UTC, zrma commented on README.md
> +Please execute src/main.py
```python
python src/main.py
```

이게 낫지 않을까요

2020-08-27 00:34 UTC, zrma commented on src/bill.py
> +        if not customer.get_is_billing() and \
이런 경우 함수명은 `get_is_billing`보다 `is_billing`이 더 직관적이지 않을까요?

영어 문법 상 `get_is_billing`은 이상하기도 하고요.

2020-08-27 00:34 UTC, zrma commented on src/bill.py
> +        if not customer.get_is_billing() and \
이런 경우 이 문맥 자체를 별도의 변수로 할당하면 코드가 조금 더 잘 읽히지 않을까요?

게다가 if 구문 안쪽에 장황하게 모든 코드를 다 넣지 않고
early return 을 잘 활용하면 코드가 조금 더 깔끔해지죠.

```python
invalid = customer.is_billing() or customer.is_waiting_billing
if invalid:
    // 무언가의 처리
    return

customer.change_waiting_billing_status()
self.__billing_waiting_queue.append(customer)
```

2020-08-27 00:34 UTC, zrma commented on src/cook.py
> +        self.__table_number, self.__customer_number, \
이 튜플이 이렇게 전개(unstructuring) 되는게 직관적이지 않아요.
[dataclass](https://docs.python.org/3/library/dataclasses.html) 또는 [namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple)을 사용해보면 어떨까요?

2020-08-27 00:34 UTC, zrma commented on src/cook.py
>          return self.__table_number, self.__customer_number,  self.__food_number
이렇게 튜플로 반환하면 이 함수의 호출부는 이 함수 내부의 구현 형태와 매우 직접적인 형태로 강결합하게 되죠.
이 함수의 호출부가 이 함수 내부 구현 모양새를 모두 알아야만 하는데 그러면 이렇게 클래스를 분리하는 의미가 사라지죠.

그래서 보통 이렇게 여러 문맥을 반환해야 할 경우 위에 언급한 것처럼 [dataclass](https://docs.python.org/3/library/dataclasses.html) 또는 [namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple)로 감싸고는 합니다.

보통 [두 메소드 사이를 메세지로 연결한다](https://ko.wikipedia.org/wiki/%EA%B2%B0%ED%95%A9%EB%8F%84)는 표현을 쓰고는 하죠.

2020-08-27 00:34 UTC, zrma commented on src/cook.py
>          return self.__is_cooking
[effective python](https://effectivepython.com/)[(구글 플레이 북 링크)](https://www.google.co.kr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjIsN3OirrrAhUiL6YKHf0XBt0QFjABegQIAhAB&url=https%3A%2F%2Fbooks.google.com%2Fbooks%3Fid%3DqZ0IDAAAQBAJ%26printsec%3Dfrontcover&usg=AOvVaw3thm2wiwFvwj8OuG9J8mBY) 을 보면 

[getter, setter 대신 일반 속성을 사용하자](https://www.pymoon.com/entry/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%97%90%EC%84%9C%EC%9D%98-getter%EC%99%80-setter)는 내용이 있습니다.

그런데 사실 더 원론적으로는 이 `self.__is_cooking` 멤버 변수를 이렇게 복잡 다단하게 관리할 필요가 있는지가 의문이에요.

2020-08-27 00:34 UTC, zrma commented on src/restaurant.py
> +                if customer.get_elapsed_waiting_time() < \
이 condition을 해당 컨텍스트를 잘 대표하는 별도의 변수로 할당하면 좋을 것 같습니다.

2020-08-27 00:34 UTC, zrma commented on src/restaurant.py
> +        customer.set_total_time(until_being_allocated +
total_time 변수를 할당해서 미리 계산한 후에 total_time을 인자로 넣거나
set_times(a, b, c) 이렇게 하는게 낫지 않을까요?

2020-08-27 00:34 UTC, zrma commented on src/restaurant.py
> +                        sorted(lower_time_group)
이런 식으로 코드를 장황하게 적으면 이 코드가 무엇을 의미하는지 이해할 수 없게 되지요.

2020-08-27 00:34 UTC, zrma commented on src/restaurant_object.py
> +from abc import ABC, abstractmethod
별도의 인터페이스를 정의해서 인터페이스를 통해서 소통하는 경우의 의도는 보통
코드 사이의 의존 고리를 끊거나 인터페이스 수준으로 최소화 하는데 있습니다.

이 정도 규모의 코드에 복잡한 형태의 상속이나 세부 구현이 있는 것도 아닌데 
abc를 사용할 필요가 있을까요?

일단 abc를 통해 인터페이스를 선언하면 각 함수의 전달 인자에 타입 힌트로 해당 추상 인터페이스를 명시하여 해당 함수 내에는 해당 인터페이스가 노출하는 함수만! 쓰도록 해야 합니다.
그런 형태로 전혀 사용하고 있지 않아요.

이 정도 규모의 코드에서 abc는 과도한 것 같아요.
최소한 어떤 의존성이 있고, 그 의존성 때문에 mocking 테스트 코드가 필요할 때
이런 인터페이스를 서술하고 그 인터페이스를 구현하는 impl mock 구현체를 사용한다
이런 형태면 모를까...

이게 자칫 잘못하면 기술 겉멋만 든 채로 뭔가를 오남용하는 상태가 될 것 같습니다.

2020-08-27 03:54 UTC, xfrnk2 commented
@zrma 
정말 고맙습니다.(_ _)
다음 이슈 해결과 함께 수정해서 PR 드릴게요!

2020-08-27 05:15 UTC, zrma commented
> @zrma
> 정말 고맙습니다.(_ _)
> 다음 이슈 해결과 함께 수정해서 PR 드릴게요!

다음 이슈 해결과 함께 수정해서 PR 하는게 아니라
이 브랜치에 그대로 수정 커밋 추가해서 Push 하면 이 PR에 계속 추가 됩니다.

2020-08-27 05:54 UTC, xfrnk2 commented
@zrma 넵

2020-08-28 01:41 UTC, zrma commented on README.md
> +Please execute src/main.py
@xfrnk2 

마크다운 문법을 공부하시는 게 좋을 것 같네요.

> \```python
> python src/main.py
> \```

2020-08-28 01:45 UTC, zrma commented on README.md
> +python src/main.py
마크다운 문법을 공부하시는 게 좋을 것 같네요.

> \```python
> python src/main.py
> \```

2020-08-28 01:45 UTC, zrma commented on src/bill.py
> +            return
여기서 바로 return 해도 되는 걸까요?

2020-08-28 01:45 UTC, zrma commented on src/bill.py
> +        if not customer.get_is_billing() and \
다음 리뷰에도 적었지만, 여기 주석에 포함한
> // 무언가의 처리

해당 부분이 빠져 있는 것 같아요.

2020-08-28 01:47 UTC, zrma commented on src/restaurant.py
> +                if customer.get_elapsed_waiting_time() < \
이건 왜 resolve 처리 하셨나요?
실수로 하신 것 같네요.

2020-08-28 01:48 UTC, zrma requested changes
PEP8 설정이 기본 한 줄에 80글자인데 이걸 140글자 정도로 변경했으면 좋겠어요.

그리고 해당 설정을 ci에도 반영해 주시고, 설정 파일 커밋 및 
해당 내용에 대한 부분이 어딘가(README.md라던가)에 기록도 명확하게 되면 좋을 것 같습니다.

2020-09-09 12:49 UTC, zrma requested changes
몇몇 군데 더 수정하면 좋을 것 같아요.

2020-09-09 12:49 UTC, zrma commented on src/cook.py
> +        self.__table_number, self.__customer_number, self.__food_number, self.__cooking_time =\
이런 건 코드 가독성이 떨어지네요.

그냥 차라리 line by line 으로 작성하면 어떨까요?

```python
self.__table_number = request.table_num
self.__customer_number = request.customer_num
self.__food_number = request.food_num
self.__cooking_time = cooking_time
```

저라면 차라리 dataclass인 `request`를 `request` 의 형태 그대로가 아니라 `food_info` 같은 걸로 정의해서  
self.__info = food_info 이와 같이 통으로 저장하고 가공 사용할거에요

2020-09-12 16:46 UTC, xfrnk2 commented on src/bill.py
> +            return
@zrma  여러번 고민해봤는데 적당한 답을 못찾은 것 같아요. 혹시 assert invalid가 필요할까요? 아직 잘 모르겠어서 도움이 필요할 것 같아요

2020-09-13 08:33 UTC, zrma requested changes
코드가 아직 장황하네요.
지엽적인 수정은 되고 있는데 큰 부분의 정리는 거의 없군요.

일단 이번에 이야기한 부분까지만 수정하고 approve하고 
다음 수정 방향을 정해서 다시 pr 열죠.

2020-09-13 08:33 UTC, zrma commented on src/bill.py
> +            return
로직 논리에 따라 살펴 보면 간단하죠.

valid 할 경우 계산대에 줄을 서죠? 그러면 자기 순번이 되면 계산을 하겠네요.

invalid 할 경우 계산대에 줄을 서지 않죠? 그러면 이 손님은 어떻게 될까요?
계산을 하지도 않고, 돌아가지도 않을까요?

2020-09-13 08:33 UTC, zrma commented on src/bill.py
> +           not self.__cash_desk_object.is_working():
`cash_desk_object` 라는 변수명은 너무 장황하기도 하고
직관적으로 무슨 의미인지 모르겠어요.

2020-09-13 08:33 UTC, zrma commented on src/cook.py
> +            if self.__info.cooking_time == 0:
여기서 `self.__info.cooking_time` 을 이런 식으로 조작하는 건 직관적이지 않은 것 같아요.

2020-09-13 08:33 UTC, zrma commented on src/kitchen.py
> +        # return all(cook.is_cooking() for cook in self.__cooks)
미사용 코드는 지우는 게 낫지 않을까요?

2020-09-13 08:33 UTC, zrma commented on src/kitchen.py
> +                        customer_food_num, customer_num, \
코드가 너무 복잡하네요.

```python
if cond:
    for loop:
        if cond:
            if cond:
````

2020-09-13 08:33 UTC, zrma commented on src/kitchen.py
> +                        """
미사용 중복코드 주석 제거

2020-09-13 08:33 UTC, zrma commented on src/restaurant.py
> +                if customer.get_elapsed_waiting_time() < \
아직도 미수정 사항

2020-09-13 16:30 UTC, xfrnk2 commented on src/bill.py
> +            return
@zrma 답변 감사합니다
고민해보니 보장해주기 위한 역할을 if invalid: 라인에서 하게끔 해야겠다는 생각이 들어서, 아래처럼 수정을 해봤어요. 왜냐면 이전까지 is_billing과 is_bill_waiting은 건드린 적이 없어서 한결같이 false였거든요. invalid한 경우가 있어서는 안되니까 계산대에 줄을 서도록 보장해주어야 할 것 같아요.
`
        if invalid:
            if customer.is_billing():
                customer.change_is_billing_status()
            if customer.is_bill_waiting():
                customer.change_is_bill_waiting_status()
            return
`
제가 짜고도 쓸데없이 길어 보이는 코드네요.. 코드 리뷰해주신것을 보면서 지엽적이지 않은 수정이 필요한 것을 느껴요. 마저 수정후 푸쉬 할게요. 감사드립니다.(_ _)

2020-09-20 11:03 UTC, zrma approved these changes
이 PR은 이 정도로 처리하고

브랜치를 하나 더 생성해서 다음 PR을 열고 코드를 더 개선 해 보아요 :) 

고생하셨습니다.

2020-09-20 11:03 UTC, zrma commented on src/cook.py
> +        return self.__info.table_num, self.__info.customer_num, self.__info.food_num
반환 값도 dataclass를 사용하면 어떨까요?

2020-09-20 11:03 UTC, zrma commented on src/restaurant.py
>                  if customer.get_elapsed_waiting_time() < customer.get_remaining_time_by_new_table():
이 조건식이 너무 장황하니 이 조건식의 로직에 해당하는 깔끔한 변수명을 할당해서 사용하면 어떨까요?

2020-09-20 11:03 UTC, zrma commented on src/bill.py
> +            return
invalid 한 상태가 논리적으로 없어야 하는 것이라면

```python
assert not invalid, "논리적으로 어쩌구저쩌구 해서 invalid 할 수 없습니다"
```

이런 것도 괜찮을 것 같아요.

그런데 더 원칙적으로는 아예 논리적으로 invalid 하지 않는다면(valid 한 상태만 있다면)  
전체적인 구조 자체가 더 변경 되어야겠는데요.

2020-09-20 11:03 UTC, zrma commented on src/cook.py
> +    def set_request(self, request: dataclass):
`set_request` 함수 말고, 아예 생성자를 통해서 첨부터 생성하는 건 어떨까 싶네요.

2020-09-20 11:03 UTC, zrma commented
> 이 PR은 이 정도로 처리하고
> 
> 브랜치를 하나 더 생성해서 다음 PR을 열고 코드를 더 개선 해 보아요 :)
> 
> 고생하셨습니다.


여기서 추가로 언급 된 내용을 포함해서 다음 PR을 시작하면 좋을 것 같네요 👍

2020-09-21 06:33 UTC, xfrnk2 commented
@zrma 정말 감사합니다 :)

2020-09-21 06:37 UTC, xfrnk2 commented
@zrma 정말 감사합니다!!! (_ _)

2020-09-21 07:06 UTC, merged