코드 개선
xfrnk2/restaurant_simulation pull request #8
Opened 2020-09-21 07:29 UTC by xfrnk2

코드 개선
새로운 브랜치 feature에서 진행

2020-09-22 13:31 UTC, zrma requested changes
코드가 조금씩 정리 되고 있어서 보기 좋군요.

더더욱 간결해지면 좋겠어요.  

단순히 글자가 중복되거나 이런 부분이 아니라  
의미적으로 같은 연산을 두 번 수행하거나  
변수가 의미하는 문맥이 겹치는 것들이 여기 저기 보이는 것 같은데  
그런 부분을 정리할 수 있으면 좋겠어요 👍

2020-09-22 13:31 UTC, zrma commented on src/bill.py
> +        if self.__cash_desk.update():
`boolean` 평가 값이 true가 나왔는데 레스토랑을 떠났다는 건 조금 이상한 것 같아요.

2020-09-22 13:31 UTC, zrma commented on src/bill.py
>          if self.__bill_waiting_queue and \
계산 대기열이 비어 있지 않고, 계산대가 비어 있다면 계산을 수행하는 건가요?

```python
def process_billing(count = 1: int):
    for _ in range(count):
        target = self.__bill_waiting_queue.pop(0)
        target.change_is_billing_status()
        target.change_is_bill_waiting_status()
        self.__cash_desk.receive_customer(target)
        self.__cash_desk.change_cash_desk_status()
```

대충 이런 함수를 하나 만들어서 처리하면 어떨까요?

2020-09-22 13:31 UTC, zrma commented on src/cook.py
>      def update(self) -> bool:
위에서 언급했지만 이 함수명은 적절할까요?

2020-09-22 13:31 UTC, zrma commented on src/cook.py
> +        if self.__cooking_time == 0:
```python
return not self.__cooking_time
# 또는
return self.__cooking_time <= 0
```

2020-09-22 13:31 UTC, zrma commented on src/customer.py
> +class Customer:
```python
def __init__(self, number: int, arrival_time: int):
    # 중략
    self.__food_eating_time = 0
    self.__food_cooking_time = 0
    # 후략
```

이 정보는 사실 food_info 하나로 퉁 쳐지는게 아닌가 싶어요.

elapsed_xxxx 시리즈도 그냥 연산 결과로 뽑혀 나올 결과물들인 것 같고요  
뭔가 중복적인 의미를 갖고 있는 변수들이 많은 것 같아요.

2020-09-22 13:31 UTC, zrma commented on src/customer.py
> +    def total_time(self, value: int):
이 total_time 은 문맥적으로 무언가를 합산 한 결과물이겠죠?  
이걸 고객의 변수로 이렇게 들고 있는게 괜찮은 걸까요?

2020-09-22 13:31 UTC, zrma commented on src/kitchen.py
> +        while self.__order_queue and len(self.__cooks) < self.__cook_number:
`start_cooking_update` 함수와 `update` 함수가 나뉘어져야 할 이유가 무엇일까요?

2020-09-22 13:31 UTC, zrma commented on src/kitchen.py
>      def update(self) -> list:
`update`를 수행했는데 `finished_order`가 반환 되는 건 이상한 것 같아요.  
적절한 함수명일까요?

2020-09-22 13:31 UTC, zrma commented on src/restaurant.py
> +                tm_sts = customer.get_remaining_time_by_new_table() <= customer.get_elapsed_waiting_time()
tm_sts 는 무슨 약자일까요?

2020-09-22 13:31 UTC, zrma commented on src/restaurant.py
> +                if can_entrance:
굳이 여기서 `else`와 `break` 조합은 이상한 것 같아요.

```python
waitable = customer.get_remaining_time_by_new_table() <= customer.get_elapsed_waiting_time()

acceptable = waitable and self.__table_manager.is_acceptable()
if not acceptable:
    break

self.customer_entrance(customer)
customer_count += 1
```

2020-09-22 13:31 UTC, zrma commented on src/restaurant.py
>              group = self.__kitchen.get_cooks_current_cooking_time()
`group` 이라는 변수명은 모호한 것 같아요.

2020-09-22 13:31 UTC, zrma commented on src/restaurant.py
>              q.append(0)
`q`의 scope가 생각보다 긴데, `q`보다는 `queue`를 모두 적어주는게 조금 더 가독성이 좋지 않을까요?

2020-09-22 13:31 UTC, zrma commented on src/restaurant.py
> +        customer.total_time = total_time
customer의 총 시간을 바깥에서 다 계산해서 다시 customer한테 넣는 건 이상한 것 같아요.

`customer.get_food_cooking_time` 이것도 customer의 정보  
`customer.get_food_eating_time` 이것도 customer의 정보인데요

`customer.set_wait_time(until_being_allocated)` 뭔기 이런 함수를 통해서  
내부에서 customer의 total_time을 결정할 수 있도록 하는 게 낫지 않을까요?

그리고 customer의 total_time을 꼭 변수로 안 들고 있어도 될 것 같은데요.

2020-09-22 13:31 UTC, zrma commented on src/table.py
> +    def getting_food(self, info: dataclass):
이 info는 무슨 info인가요?

2020-09-22 13:31 UTC, zrma commented on src/table.py
> +            print(f"{info.customer_num}번 손님이 식사를 시작합니다.")
이 info가 table_num도 알고 있고, customer_num도 알고 있는 뭔가 복합적이고 전지전능한 객체인가보네요?

2020-09-22 13:32 UTC, zrma commented
#7 의 문제도 이 PR에서 해결 할 수 있으면 좋을 것 같아요.

2020-09-28 10:58 UTC, xfrnk2 commented
@zrma 정말 감사합니다 (_ _)

2020-10-01 10:46 UTC, zrma requested changes
CI가 실패하면 

우선 정상적인 CI를 셋팅하는 게 먼저고  
설정이 정상인데 실패한다면
CI를 느슨하게 할 게 아니라 CI가 실패하는 코드를 수정해야죠. 

코드가 조금 간결하게 정리 되는 것 같은데...
이번 리뷰도 이번 리뷰 반영 정도만 하고 병합 하고  
그 다음 개선은 또 다름 PR로 진행해보죠.

2020-10-01 10:46 UTC, zrma commented on setup.cfg
> +max-complexity = 10
빌드 깨지는 것 때문에 이 값을 높이지 마시고
`max-complexity` 제한 값인 8에 맞춰서 코드를 리팩토링 하시죠.

이건 되돌리는 게 낫겠어요.

2020-10-01 10:46 UTC, zrma commented on src/bill.py
> +class BillManager:
`CachDesck`는 뭐고 `BillManager`는 뭘까요?  
이걸 두 개로 쪼갤 필요가 있을까요?

2020-10-01 10:46 UTC, zrma commented on src/cook.py
>      def update(self) -> bool:
`update`라는 함수가 `boolean` 자료형을 반환하면 이 `boolean`은 어떻게 해석해야 할까요?

2020-10-01 10:46 UTC, zrma commented on src/customer.py
> +        self.__remaining_time_by_new_table = value
이 변수는 변수명만 봐서 무슨 역할을 하는지 모르겠어요.

그리고 와 getter, setter가 필요한걸까요?

2020-10-01 10:46 UTC, zrma commented on src/customer.py
> +        self.__remaining_time_by_new_table = value
여전히 이 파일에 getter/setter property가 너무 많아 보여요

2020-10-01 10:46 UTC, zrma commented on src/kitchen.py
> +        if finished_order:
이 if 구문이 필요한가요?

2020-10-01 10:46 UTC, zrma commented on src/restaurant.py
>          while elapsed_time < 720:
이 함수는 조금 장황해 보이네요.

2020-10-01 10:46 UTC, zrma commented on src/table.py
> +    def getting_food(self, table_num: int):
TableManager의 멤버 변수의 정확한 index를 외부에서 알아야 하는가 생각해 볼 문제네요.

2020-10-06 09:28 UTC, merged

2020-10-10 11:49 UTC, xfrnk2 commented on setup.cfg
> +max-complexity = 10
@zrma 감사합니다!