코드 개선 2
xfrnk2/restaurant_simulation pull request #9
Opened 2020-10-10 11:44 UTC by xfrnk2

2020-10-13 05:31 UTC, zrma requested changes
우선 이 정도만 수정해 보죠.

2020-10-13 05:31 UTC, zrma commented on src/bill.py
>          self.__is_working = not self.__is_working
이거 이렇게 하면 True ↔ False 를 반복하지 않나요?

2020-10-13 05:31 UTC, zrma commented on src/bill.py
> +            self.change_working_status()
이러면 status가 True ↔ False 로 진동할텐데 count 1일때는 뭐 그렇다 치고 count > 1일때는 뭔가 이상한 것 같은데요.

2020-10-13 05:31 UTC, zrma commented on src/bill.py
> +            self.change_working_status()
process_billing 과 update 가 각각 번갈아 한 번씩 동작한다고 가정하고 만든 코드인 것 같네요.

그런데 두 함수가 저렇게 쪼개져 있어서 연관성이 없어 보여요.

2020-10-13 05:31 UTC, zrma commented on src/restaurant.py
> +        is_true = elapsed_time < 720
`is_true`보다 더 직관적인 변수명이 좋을 것 같아요.

2020-10-15 16:56 UTC, xfrnk2 commented on src/bill.py
> +            self.change_working_status()
@zrma 
정말 그런 것 같아요. 해주신 말씀을 참고해서 계산대가 여러대일것을 가정해서 계산대들을 가리키는 새로운 변수 self.__desks를 만들고, 매 tick마다 1씩 줄어들도록 해서 이전과 같은 조건(계산수행시간이 0이 되면 계산대가 일을 멈추고 다른 손님을 받는) 형태로 변경했어요.

2020-10-16 10:53 UTC, zrma approved these changes
일단 이 PR은 이렇게 하는 걸로 정리하시죠  
그리고 이제 이 코드에 TDD를 적용해 보도록 해요.

[travis ci 결과](https://travis-ci.com/github/xfrnk2/restaurant_simulation/builds/190410637)를 살펴보면 CI가 계속 실패하고 있는데  
우선 이것을 성공하도록 되돌린 후에 

테스트 코드를 조금씩 추가하여  
프로젝트 전체의 테스트 커버리지가 70% 이상 도달하도록 해 보죠.

사실 지금 코드는 너무 장황하고 복잡해서  
리뷰 하기도 힘들고 눈에도 잘 안 들어와요.

그래서 코드가 정상적으로 동작하는지 파악 할 수 없어요.
올바른 코드 리뷰가 되지 않을 것 같아요.

따라서 작은 규모부터 시작해서 테스트 코드를 적용해서  
전체 커버리지를 끌어올리도록 하죠.

잘 작성한 테스트 코드는 코드의 역할을 파악하기 쉽게 합니다.

2020-10-16 10:53 UTC, zrma commented on src/bill.py
> +        while self.__waiting_queue and len(self.__desks) < 3:
@xfrnk2 
이 하드코딩 숫자 `3`은 뭔가요?

2020-10-19 03:12 UTC, merged

2020-10-19 03:27 UTC, xfrnk2 commented
@zrma 감사합니다 (_ _)

2020-10-19 03:29 UTC, xfrnk2 commented on src/bill.py
> +        while self.__waiting_queue and len(self.__desks) < 3:
@zrma 계산대의 수를 나타내려고 했는데 그냥 지나갔던 것 같아요. 초기화 함수 전달 인자로 계산대의 수를 받아와서 멤버 변수에 저장하도록 변경했어요.